apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: python-helloworld-server
    app.kubernetes.io/part-of: python-helloworld
  name: python-helloworld-server-nodeport
  namespace: python-helloworld
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5000
    nodePort: 30009
  - name: https
    port: 443
    protocol: TCP
    targetPort: 5000
    nodePort: 30010
  selector:
    app.kubernetes.io/name: python-helloworld-server
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
